kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb-spark
subjects:
- kind: ServiceAccount
  name: sa-spark
  namespace: default
roleRef:
  kind: ClusterRole
  name: cr-spark
  apiGroup: rbac.authorization.k8s.io